import "~/styles/globals.css";

import { GeistSans, GeistMono } from 'geist/font'
import { type Metadata } from "next";
import { Inter } from 'next/font/google';
import { Space_Grotesk, Space_Mono } from 'next/font/google';

import ChatbotWidget from "../components/ChatbotWidget";

const inter = Inter({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter'
});

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
});

const spaceMono = Space_Mono({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-space-mono',
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable} ${spaceGrotesk.variable} ${spaceMono.variable}`}>
      <body className="font-sans antialiased">
        <div className="w-full max-w-[100vw] overflow-x-hidden">
          {children}
          <ChatbotWidget />
        </div>
      </body>
    </html>
  );
}
